// Generated by tooling/discover-modules.mjs. Module discovery requires no host edits.
import type { ModuleDefinition } from "@suite/module-sdk";
import m0 from "../../../modules/contacts/module";
import m1 from "../../../modules/inventory/module";
import m2 from "../../../modules/orders/module";
import m3 from "../../../modules/projects/module";
export const bundledModuleDefinitions: readonly ModuleDefinition[] =
  Object.freeze([m0, m1, m2, m3]);
export const moduleDefinitions: ModuleDefinition[] = [
  ...bundledModuleDefinitions,
];
export const bundledModuleIds: readonly string[] = Object.freeze(
  moduleDefinitions.map((m) => m.id),
);
export function registerModule(module: ModuleDefinition) {
  const i = moduleDefinitions.findIndex((m) => m.id === module.id);
  if (i < 0) moduleDefinitions.push(module);
  else moduleDefinitions[i] = module;
}
export const moduleDefinition = (id: string) =>
  moduleDefinitions.find((m) => m.id === id);
export function moduleDependencies(id: string, path: string[] = []): string[] {
  if (path.includes(id))
    throw Error("Circular module dependency: " + [...path, id].join(" -> "));
  const m = moduleDefinition(id);
  if (!m) throw Error("Unknown module: " + id);
  return [
    ...new Set([
      ...Object.keys(m.dependencies).flatMap((d) =>
        moduleDependencies(d, [...path, id]),
      ),
      id,
    ]),
  ];
}
