import { readdir, writeFile, readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { format } from "prettier";
const rootFlag = process.argv.indexOf("--root");
if (rootFlag >= 0 && !process.argv[rootFlag + 1])
  throw Error("--root requires a workspace directory.");
const root =
  rootFlag >= 0 ? resolve(process.argv[rootFlag + 1]) : process.cwd();
const workspacePath = (...parts) => resolve(root, ...parts);
const dirs = (await readdir(workspacePath("modules"), { withFileTypes: true }))
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();
const modules = [];
for (const dir of dirs) {
  try {
    await readFile(workspacePath("modules", dir, "module.ts"));
    const manifest = JSON.parse(
      await readFile(workspacePath("modules", dir, "package.json"), "utf8"),
    );
    if (!manifest.name || !manifest.exports?.["."])
      throw Error(`Module ${dir} must publish its module.ts entry.`);
    modules.push({ dir, name: manifest.name, exports: manifest.exports });
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
}
const imports = modules
  .map((module, i) => `import m${i} from '${module.name}';`)
  .join("\n");
const catalog = `// Generated by tooling/modules/discover-modules.mjs. Module discovery requires no host edits.
import type {ModuleDefinition} from '@suite/module-sdk';
import {createModuleCatalog} from '@suite/module-sdk/catalog';
${imports}
export const bundledModuleDefinitions:readonly ModuleDefinition[]=Object.freeze([${modules.map((_, i) => `m${i}`).join(",")}]);
export const moduleCatalog=createModuleCatalog(bundledModuleDefinitions);
export const moduleDefinitions=moduleCatalog.modules as ModuleDefinition[];
export const bundledModuleIds:readonly string[]=Object.freeze(bundledModuleDefinitions.map(m=>m.id));
export const registerModule=(module:ModuleDefinition)=>moduleCatalog.register(module);
export const moduleDefinition=(id:string)=>moduleCatalog.definition(id);
export const moduleDependencies=(id:string)=>moduleCatalog.dependencies(id);`;
const servers = [];
function hasExport(module, subpath) {
  return Object.keys(module.exports).some((key) => {
    if (key === subpath) return true;
    if (!key.includes("*")) return false;
    const [before, after] = key.split("*");
    return subpath.startsWith(before) && subpath.endsWith(after);
  });
}
async function entry(module, path, subpath) {
  try {
    await readFile(workspacePath("modules", module.dir, `${path}.ts`));
    if (!hasExport(module, subpath))
      throw Error(`${module.name} must export ${subpath}.`);
    servers.push(`${module.name}${subpath.slice(1)}`);
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
}
for (const module of modules) {
  await entry(module, "module-server", "./module-server");
  let releases = [];
  try {
    releases = await readdir(workspacePath("modules", module.dir, "releases"), {
      withFileTypes: true,
    });
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
  for (const release of releases
    .filter((r) => r.isDirectory())
    .sort((a, b) => a.name.localeCompare(b.name)))
    await entry(
      module,
      `releases/${release.name}/module-server`,
      `./releases/${release.name}/module-server`,
    );
}
const serverCatalog = `// Generated reviewed server entry points. Never import this file into a renderer.
import type {ScopedModuleServer,TrustedModuleServer} from '@suite/module-sdk/server';
import type {Tx,Context} from '@suite/server-core';
${servers.map((specifier, i) => `import s${i} from '${specifier}';`).join("\n")}
const staged:Array<ScopedModuleServer|TrustedModuleServer<{tx:Tx;ctx:Context}>>=[${servers.map((_, i) => `s${i}`).join(",")}];
const identities=new Map<string,(typeof staged)[number]>();
for(const server of staged){const key=server.module.id+'@'+server.module.version;const previous=identities.get(key);if(previous && previous!==server)throw Error('Duplicate staged backend: '+key);identities.set(key,server);}
export const moduleServers=[...identities.values()];
`;
const locals = [];
for (const module of modules) {
  try {
    await readFile(workspacePath("modules", module.dir, "module-local.ts"));
    if (!hasExport(module, "./module-local"))
      throw Error(`${module.name} must export ./module-local.`);
    locals.push(`${module.name}/module-local`);
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
}
const localCatalog = `// Generated reviewed local handlers. Import only from a dedicated worker.
import type {LocalModule} from '@suite/module-sdk/local';
${locals.map((specifier, i) => `import l${i} from '${specifier}';`).join("\n")}
export const localModules:LocalModule[]=[${locals.map((_, i) => `l${i}`).join(",")}];`;
for (const [path, source] of [
  ["index", catalog],
  ["server", serverCatalog],
  ["local", localCatalog],
]) {
  const file = workspacePath("composition", "src", "catalog", `${path}.ts`);
  const output = await format(source, { parser: "typescript" });
  let previous;
  try {
    previous = await readFile(file, "utf8");
  } catch {}
  if (previous !== output) await writeFile(file, output);
}
console.log(
  `Discovered ${modules.length} modules and ${servers.length} server entry points.`,
);

const compositionManifestPath = workspacePath("composition", "package.json");
const compositionManifest = JSON.parse(
  await readFile(compositionManifestPath, "utf8"),
);
compositionManifest.dependencies ??= {};
compositionManifest.suite ??= {};
const previousGenerated = Array.isArray(
  compositionManifest.suite.generatedModuleDependencies,
)
  ? compositionManifest.suite.generatedModuleDependencies
  : [];
for (const dependency of previousGenerated)
  delete compositionManifest.dependencies[dependency];
for (const module of modules)
  compositionManifest.dependencies[module.name] = "workspace:*";
compositionManifest.suite.generatedModuleDependencies = modules.map(
  (module) => module.name,
);
const formattedManifest = await format(JSON.stringify(compositionManifest), {
  parser: "json",
});
if ((await readFile(compositionManifestPath, "utf8")) !== formattedManifest)
  await writeFile(compositionManifestPath, formattedManifest);
