// Generated by tooling/modules/discover-modules.mjs. Module discovery requires no host edits.
import type { ModuleDefinition } from "@suite/module-sdk";
import { createModuleCatalog } from "@suite/module-sdk/catalog";
import m0 from "@suite/contacts";
import m1 from "@suite/inventory";
import m2 from "@suite/orders";
import m3 from "@suite/projects";
export const bundledModuleDefinitions: readonly ModuleDefinition[] =
  Object.freeze([m0, m1, m2, m3]);
export const moduleCatalog = createModuleCatalog(bundledModuleDefinitions);
export const moduleDefinitions = moduleCatalog.modules as ModuleDefinition[];
export const bundledModuleIds: readonly string[] = Object.freeze(
  bundledModuleDefinitions.map((m) => m.id),
);
export const registerModule = (module: ModuleDefinition) =>
  moduleCatalog.register(module);
export const moduleDefinition = (id: string) => moduleCatalog.definition(id);
export const moduleDependencies = (id: string) =>
  moduleCatalog.dependencies(id);
