import { readdir, writeFile, readFile } from "node:fs/promises";
import { format } from "prettier";
const dirs = (await readdir("modules", { withFileTypes: true }))
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();
const modules = [];
for (const dir of dirs) {
  try {
    await readFile(`modules/${dir}/module.ts`);
    modules.push(dir);
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
}
const imports = modules
  .map((d, i) => `import m${i} from '../../../modules/${d}/module';`)
  .join("\n");
const catalog = `// Generated by tooling/discover-modules.mjs. Module discovery requires no host edits.
import type {ModuleDefinition} from '@suite/module-sdk';
${imports}
export const moduleDefinitions:ModuleDefinition[]=[${modules.map((_, i) => `m${i}`).join(",")}];
export const bundledModuleIds:readonly string[]=Object.freeze(moduleDefinitions.map(m=>m.id));
export function registerModule(module:ModuleDefinition){const i=moduleDefinitions.findIndex(m=>m.id===module.id);if(i<0)moduleDefinitions.push(module);else moduleDefinitions[i]=module;}
export const moduleDefinition=(id:string)=>moduleDefinitions.find(m=>m.id===id);
export function moduleDependencies(id:string,path:string[]=[]):string[]{
 if(path.includes(id))throw Error('Circular module dependency: '+[...path,id].join(' -> '));
 const m=moduleDefinition(id);if(!m)throw Error('Unknown module: '+id);
 return [...new Set([...Object.keys(m.dependencies).flatMap(d=>moduleDependencies(d,[...path,id])),id])];
}`;
const servers = [];
async function entry(path) {
  try {
    await readFile(`modules/${path}.ts`);
    servers.push(path);
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
}
for (const dir of modules) {
  await entry(`${dir}/module-server`);
  let releases = [];
  try {
    releases = await readdir(`modules/${dir}/releases`, {
      withFileTypes: true,
    });
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
  for (const release of releases
    .filter((r) => r.isDirectory())
    .sort((a, b) => a.name.localeCompare(b.name)))
    await entry(`${dir}/releases/${release.name}/module-server`);
}
const serverCatalog = `// Generated reviewed server entry points. Never import this file into a renderer.
import type {ScopedModuleServer,TrustedModuleServer} from '@suite/module-sdk/server';
import type {Tx,Context} from '../../server-core/src';
${servers.map((d, i) => `import s${i} from '../../../modules/${d}';`).join("\n")}
export const moduleServers:Array<ScopedModuleServer|TrustedModuleServer<{tx:Tx;ctx:Context}>>=[${servers.map((_, i) => `s${i}`).join(",")}];
const identities=new Set<string>();
for(const server of moduleServers){const key=server.module.id+'@'+server.module.version;if(identities.has(key))throw Error('Duplicate staged backend: '+key);identities.add(key);}
`;
for (const [path, source] of [
  ["index", catalog],
  ["server", serverCatalog],
]) {
  const file = `packages/module-catalog/src/${path}.ts`;
  const output = await format(source, { parser: "typescript" });
  let previous;
  try {
    previous = await readFile(file, "utf8");
  } catch {}
  if (previous !== output) await writeFile(file, output);
}
console.log(
  `Discovered ${modules.length} modules and ${servers.length} staged backends.`,
);
